groupchat/urls.py
from django.urls import path
from . import views

app_name = 'groupchat'

urlpatterns = [
   
    path('home/', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),

    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),

    path('update-user/', views.updateUser, name="update-user"),

    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
]

map/urls.py
from django.urls import path
from .views import index
app_name = "map"

urlpatterns = [
    path('index/', index, name='index'),
]

privetchat/urls.py
from django.urls import path
from . import views

app_name = 'privetchat'

urlpatterns = [
   
    path('home/', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),
    
    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
]








# from django.urls import path

# from . import views

# app_name = 'privetchat'

# urlpatterns = [
#     path('home/', views.home, name='home'),
#     path('chat/<int:sender_id>/<int:receiver_id>/', views.chat_between_users, name='chat_between_users'),
# ]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls',namespace="base")),
    path('groupchat/', include('groupchat.urls' , namespace="groupchat")),
    path('account/', include('account.urls', namespace="account")),
    path('basket/', include('basket.urls', namespace="basket")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    path('privetchat/', include('privetchat.urls', namespace="privetchat")),
    path('promotion/', include('promotion.urls', namespace="promotion")),
    path('map/', include('map.urls', namespace="map")),
    path('api/', include('groupchat.api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

privetchat/models.py
from django.db import models
from account.models import Customer
from base.models import Doctors


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(Doctors,related_name='user', on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic,related_name='topic', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(Customer, related_name='participant',blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(Customer,related_name='users', on_delete=models.CASCADE)
    room = models.ForeignKey(Room,related_name='room', on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

privetchat/forms.py
from django.forms import ModelForm

from .models import Room
from account.models import Customer




class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['avatar', 'name', 'email', 'bio']

privetchat/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Room, Topic, Message
from account.models import Customer
from  .forms import UserForm,RoomForm







def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )

    topics = Topic.objects.all()[0:5]
    room_count = rooms.count()
    room_messages = Message.objects.filter(
        Q(room__topic__name__icontains=q))[0:3]

    context = {'rooms': rooms, 'topics': topics,
               'room_count': room_count, 'room_messages': room_messages}
    return render(request, 'privetchat/home.html', context)


def room(request, pk):
    room = Room.objects.get(id=pk)
    # room_messages = room.Message.all()
    participants = room.participants.all()

    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('privetchat:room', pk=room.id)

    context = {'room': room, 
               'participants': participants}
    return render(request, 'privetchat/room.html', context)

@login_required(login_url='login')
def userProfile(request, pk):
    user = Customer.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user': user, 'rooms': rooms,
               'room_messages': room_messages, 'topics': topics}
    return render(request, 'privetchat/profile.html', context)


@login_required(login_url='login')
def createRoom(request):
    if request.user != user.is_staff:
        return HttpResponse('Your are not allowed here!!')
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
        )
        return redirect('privetchat:home')

    context = {'form': form, 'topics': topics}
    return render(request, 'privetchat/room_form.html', context)


@login_required(login_url='login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()
    if request.user != room.host:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        return redirect('home')

    context = {'form': form, 'topics': topics, 'room': room}
    return render(request, 'base/room_form.html', context)


@login_required(login_url='login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        room.delete()
        return redirect('home')
    return render(request, 'privechat/delete.html', {'obj': room})


@login_required(login_url='login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        message.delete()
        return redirect('private:home')
    return render(request, 'privetchat/delete.html', {'obj': message})


@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('privetchat:user-profile', pk=user.id)

    return render(request, 'privet/update-user.html', {'form': form})


def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    return render(request, 'privetchat/topics.html', {'topics': topics})


def activityPage(request):
    room_messages = Message.objects.all()
    return render(request, 'privetchat/activity.html', {'room_messages': room_messages})



# from django.http import JsonResponse

# def submit_rating(request):
#     if request.method == 'POST':
#         rating = request.POST.get('rating')
#         # Perform any validation or processing of the rating value here

#         # Update the hospital_rating in your Django model accordingly
#         # Assuming you have a Hospital model with a hospital_rating field
#         hospital = Hospital.objects.get(pk=1)  # Replace 1 with the actual hospital record you want to update
#         hospital.hospital_rating = rating
#         hospital.save()

#         return JsonResponse({'success': True})
#     else:
#         return JsonResponse({'success': False, 'message': 'Invalid request method'})

privetchat/templates/privetchat/activity_component.html
<div class="activities">
    <div class="activities__header">
        <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'groupchat:user-profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                </div>
                <p>
                    @{{message.user.username}}
                    <span>{{message.created|timesince}} ago</span>
                </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
                <a href="{% url 'groupchat:delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {% endif %}

        </div>
        <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'privetchat:room' message.room.id %}">{{message.room}}</a>”</p>
            <div class="activities__boxRoomContent">{{message.body|slice:150}}<h4>more..</h4></div>
        </div>
    </div>
    {% endfor %}

</div>

privetchat/templates/privetchat/delete.html
{% extends 'main.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{obj}}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

privetchat/templates/privetchat/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="#" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{room.host.avatar.url}}" />
            </div>
            <span>@{{room.host.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{room.created|timesince}} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'privetchat:room' room.id %}">{{room.name}}</a>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'privetchat:room' room.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{room.participants.all.count}} Joined
        </a>
        <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
</div>
{% endfor %}

privetchat/templates/privetchat/home.html
{% extends 'main.html' %}

{% block content %}

<main class="layout layout--3">
  <div class="container">

    <!-- Topics Start -->
    {% include 'privetchat/topics_component.html' %}

    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'privetchat:home' %}" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'privetchat:topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="{% url 'privetchat:activity' %}">Recent Activities</a>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Chat Rooms</h2>
          <p>{{room_count}} Rooms available</p>
        </div>

   
      </div>

      {% include 'privetchat/feed_component.html' %}

    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'privetchat/activity_component.html' %}

    <!-- Activities End -->
  </div>
</main>

{% endblock %}

privetchat/templates/privetchat/home_old.html
{% extends 'base.html' %}

{% block content %}

<style>
    .home-container {
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>


<div class="home-container">

    <div>
        {% include 'base/topics_component.html' %}
    </div>

    <div>
        <h5>{{room_count}} rooms available</h5>
        <a href="{% url 'create-room' %}">Create Room</a>

        {% include 'base/feed_component.html' %}

    </div>


    <div>
        {% include 'base/activity_component.html' %}
    </div>



</div>

{% endblock content %}

privetchat/templates/privetchat/profile.html
{% extends 'base.html' %}

{% block content %}
<main class="profile-page layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'privetchat/topics_component.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="profile">
        <div class="profile__avatar">
          <div class="avatar avatar--large active">
            <img src="{{user.avatar.url}}" />
          </div>
        </div>
        <div class="profile__info">
          <h3>{{user.name}}</h3>
          <p>@{{user.name}}</p>
          {% if request.user == user %}
          <a href="{% url 'privetchat:update-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
          {% endif %}
        </div>
        <div class="profile__about">
          <h3>About</h3>
          <p>
            {{user.bio}}
          </p>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Room Hosted by {{user.name}}</a>
          </h2>
        </div>
      </div>
      {% include 'privechat/feed_component.html' %}


    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'privetchat/activity_component.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock content %}

privetchat/templates/privetchat/profile_old.html
{% extends 'main.html' %}

{% block content %}

<style>
    .profile-container {
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<h1>{{user.username}}</h1>

<div class="profile-container">
    <div>
        {% include 'base/topics_component.html' %}
    </div>

    <div>
        {% include 'base/feed_component.html' %}
    </div>

    <div>
        {% include 'base/activity_component.html' %}
    </div>
</div>

{% endblock content %}

privetchat/templates/privetchat/room.html
{% extends 'main.html' %}

{% block content %}
<main class="profile-page layout layout--2">
  <div class="container">
    <!-- Room Start -->
    <div class="room">
      <div class="room__top">
        <div class="room__topLeft">
          <a href="{% url 'privetchat:home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Study Room</h3>
        </div>
        {% if room.host == request.user %}
        <div class="room__topRight">
          <a href="{% url 'privetchat:update-room' room.id %}">
            <svg enable-background="new 0 0 24 24" height="32" viewBox="0 0 24 24" width="32"
              xmlns="http://www.w3.org/2000/svg">
              <title>edit</title>
              <g>
                <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
              </g>
              <g>
                <g>
                  <path
                    d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z" />
                </g>
                <g>
                  <path
                    d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z" />
                </g>
              </g>
            </svg>
          </a>
          <a href="{% url 'privetchat:delete-room' room.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
              </path>
            </svg>
          </a>
        </div>
        {% endif %}

      </div>
      <div class="room__box scroll">
        <div class="room__header scroll">
          <div class="room__info">
            <h3>{{room.name}}</h3>
            <span>{{room.created|timesince}} ago</span>
          </div>
          {% comment %} <div class="room__hosted">
            <p>Hosted By</p>
            <a href="{% url 'privetchat:user-profile' room.host.id %}" class="room__author">
              <div class="avatar avatar--small">
                <img src="{{room.host.avatar.url}}" />
              </div>
              <span>@{{room.host.name}}</span>
            </a>
          </div>
          <span class="room__topics">{{room.topic}}</span>
        </div> {% endcomment %}

        <div class="room__conversation">
          <div class="threads scroll">


            {% for message in room_messages %}
            <div class="thread">
              <div class="thread__top">
                <div class="thread__author">
                  <a href="{% url 'privetchat:user-profile' message.user.id %}" class="thread__authorInfo">
                    <div class="avatar avatar--small">
                      <img src="{{message.user.avatar.url}}" />
                    </div>
                    <span>@{{message.user.username}}</span>
                  </a>
                  <span class="thread__date">{{message.created|timesince}} ago</span>
                </div>

                {% if request.user == message.user %}
                <a href="{% url 'privetchat:delete-message' message.id %}">
                  <div class="thread__delete">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                      </path>
                    </svg>
                  </div>
                </a>
                {% endif %}
              </div>
              <div class="thread__details">
                {{message.body}}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>

      </div>
      <div class="room__message">
        <form action="" method="POST">
          {% csrf_token %}
          <input name="body" placeholder="Write your message here..." />
        </form>
      </div>
    </div>
    <!-- Room End -->

    <!--   Start -->
    {% comment %} <div class="participants">
      <h3 class="participants__top">Participants <span>({{participants.count}} Joined)</span></h3>
      <div class="participants__list scroll">
        {% for user in participants %}
        <a href="{%  url 'privetchat:user-profile' user.id %}" class="participant">
          <div class="avatar avatar--medium">
            <img src="{{user.avatar.url}}" />
          </div>
          <p>
            {{user.name}}
            <span>@{{user.username}}</span>
          </p>
        </a>
        {% endfor %}
      </div>
    </div> {% endcomment %}
    <!--  End -->
  </div>
</main>
<script src="script.js"></script>
{% endblock content %}

privetchat/templates/privetchat/room_form.html
{% extends 'main.html' %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{{request.META.HTTP_REFERER}}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Create/Update Study Room</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST">
          {% csrf_token %}

          <div class="form__group">
            <label for="room_topic">Enter a Topic</label>
            <input required type="text" value="{{room.topic.name}}" name="topic" list="topic-list" />
            <datalist id="topic-list">
              <select id="room_topic">
                {% for topic in topics %}
                <option value="{{topic.name}}">{{topic.name}}</option>
                {% endfor %}
              </select>
            </datalist>
          </div>


          <div class="form__group">
            <label for="room_name">Room Name</label>
            {{form.name}}
          </div>

          <div class="form__group">
            <label for="room_description">Room Description</label>
            {{form.description}}
          </div>


          <div class="form__action">
            <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
            <button class="btn btn--main" type="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

privetchat/templates/privetchat/topics_component.html
<div class="topics">
    <div class="topics__header">
        <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
        <li>
            <a href="{% url 'privetchat:home' %}" class="active">All <span>{{topics.count}}</span></a>
        </li>
        {% for topic in topics %}
        <li>
            <a href="{% url 'privetchat:home' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>
        </li>
        {% endfor %}

    </ul>
    <a class="btn btn--link" href="{% url 'privetchat:topics' %}">
        More
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>chevron-down</title>
            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
        </svg>
    </a>
</div>

privetchat/templates/privetchat/update-user.html
{% extends 'main.html' %}

{% block content %}
<main class="update-account layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'groupchat:home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Edit your profile</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          {% for field in form %}
          <div class="form__group">
            <label for="profile_pic">{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}


          <div class="form__action">
            <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
            <button class="btn btn--main" type="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  </div>
</main>
{% endblock content %}