base/urls.py
from django.urls import path
from . import views
from .views import doctor_list, doctor_detail
app_name = 'base'

urlpatterns = [


    path('', views.hospital_all, name='store_home'),
    path('hospital_all/', views.hospital_all, name='hospital_all'),
    path('dashboard-index/', views.index, name='dashboard-index'),
    # path('hospital/<slug:slug>/', views.map, name='hospital_map'),
    path('hospital<slug:slug>', views.hospital_detail, name='hospital_detail'),
    path('hospital/<slug:category_slug>/', views.category_list, name='category_list'),
    path('save_location/',views.save_location, name='save_location'),
    path('doctor-list/', doctor_list, name='doctor_list'),
    path('doctor-detail/<slug:slug>/', doctor_detail, name='doctor_detail'),
    path('staff_apply_leave/', views.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save/', views.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback/', views.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save/', views.staff_feedback_save, name="staff_feedback_save"),
    path('users_feedback_message/', views.users_feedback_message, name="users_feedback_message"),
    path('users_feedback_message_reply/', views.users_feedback_message_reply, name="users_feedback_message_reply"),
    path('staff_feedback_message/', views.staff_feedback_message, name="staff_feedback_message"),
    path('staff_feedback_message_reply/', views.staff_feedback_message_reply, name="staff_feedback_message_reply"),
    path('staff_leave_view/', views.staff_leave_view, name="staff_leave_view"),
    path('staff_leave_approve/<leave_id>/', views.staff_leave_approve, name="staff_leave_approve"),
    path('staff_leave_reject/<leave_id>/', views.staff_leave_reject, name="staff_leave_reject"),
    path('users_feedback/', views.users_feedback, name="users_feedback"),
    path('users_feedback_save/', views.users_feedback_save, name="users_feedback_save"),
    path("services/", views.services, name="services"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path('users_message/', views.users_message, name="users_message"),
    path('users_message_save/', views.users_message_save, name="users_message_save"),
    path('users_message_view/', views.users_message_view, name="users_message_view"),
    path('users_message_reply/', views.users_message_reply, name="users_message_reply"),


    
]

map/urls.py
from django.urls import path
from .views import index
app_name = "map"

urlpatterns = [
    path('index/', index, name='index'),
]

privetchat/urls.py
from django.urls import path
from . import views

app_name = 'privetchat'

urlpatterns = [
   
    path('home/', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),
    
    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
]








# from django.urls import path

# from . import views

# app_name = 'privetchat'

# urlpatterns = [
#     path('home/', views.home, name='home'),
#     path('chat/<int:sender_id>/<int:receiver_id>/', views.chat_between_users, name='chat_between_users'),
# ]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls',namespace="base")),
    path('groupchat/', include('groupchat.urls' , namespace="groupchat")),
    path('account/', include('account.urls', namespace="account")),
    path('basket/', include('basket.urls', namespace="basket")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    path('privetchat/', include('privetchat.urls', namespace="privetchat")),
    path('promotion/', include('promotion.urls', namespace="promotion")),
    path('map/', include('map.urls', namespace="map")),
    path('api/', include('groupchat.api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

privetchat/models.py
from django.db import models
from account.models import Customer
from base.models import Doctors


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(Doctors,related_name='user', on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic,related_name='topic', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(Customer, related_name='participant',blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(Customer,related_name='users', on_delete=models.CASCADE)
    room = models.ForeignKey(Room,related_name='room', on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

privetchat/forms.py
from django.forms import ModelForm

from .models import Room
from account.models import Customer




class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['avatar', 'name', 'email', 'bio']

privetchat/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Room, Topic, Message
from account.models import Customer
from  .forms import UserForm,RoomForm







def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )

    topics = Topic.objects.all()[0:5]
    room_count = rooms.count()
    room_messages = Message.objects.filter(
        Q(room__topic__name__icontains=q))[0:3]

    context = {'rooms': rooms, 'topics': topics,
               'room_count': room_count, 'room_messages': room_messages}
    return render(request, 'privetchat/home.html', context)


def room(request, pk):
    room = Room.objects.get(id=pk)
    # room_messages = room.Message.all()
    participants = room.participants.all()

    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('privetchat:room', pk=room.id)

    context = {'room': room, 
               'participants': participants}
    return render(request, 'privetchat/room.html', context)

@login_required(login_url='login')
def userProfile(request, pk):
    user = Customer.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user': user, 'rooms': rooms,
               'room_messages': room_messages, 'topics': topics}
    return render(request, 'privetchat/profile.html', context)


@login_required(login_url='login')
def createRoom(request):
    if request.user != user.is_staff:
        return HttpResponse('Your are not allowed here!!')
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
        )
        return redirect('privetchat:home')

    context = {'form': form, 'topics': topics}
    return render(request, 'privetchat/room_form.html', context)


@login_required(login_url='login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()
    if request.user != room.host:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        return redirect('home')

    context = {'form': form, 'topics': topics, 'room': room}
    return render(request, 'base/room_form.html', context)


@login_required(login_url='login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        room.delete()
        return redirect('home')
    return render(request, 'privechat/delete.html', {'obj': room})


@login_required(login_url='login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        message.delete()
        return redirect('private:home')
    return render(request, 'privetchat/delete.html', {'obj': message})


@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('privetchat:user-profile', pk=user.id)

    return render(request, 'privet/update-user.html', {'form': form})


def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    return render(request, 'privetchat/topics.html', {'topics': topics})


def activityPage(request):
    room_messages = Message.objects.all()
    return render(request, 'privetchat/activity.html', {'room_messages': room_messages})



# from django.http import JsonResponse

# def submit_rating(request):
#     if request.method == 'POST':
#         rating = request.POST.get('rating')
#         # Perform any validation or processing of the rating value here

#         # Update the hospital_rating in your Django model accordingly
#         # Assuming you have a Hospital model with a hospital_rating field
#         hospital = Hospital.objects.get(pk=1)  # Replace 1 with the actual hospital record you want to update
#         hospital.hospital_rating = rating
#         hospital.save()

#         return JsonResponse({'success': True})
#     else:
#         return JsonResponse({'success': False, 'message': 'Invalid request method'})

templates/privetchat/staff_apply_leave_template.html
{% extends "../sub_base.html" %}


{% block page_title %}
    Leave Report and Apply for Leave
{% endblock page_title %}
{% block sub_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Apply For Leave</h3>
                    </div>
                    <!-- /.card-header -->

                                {% comment %} Display Messages {% endcomment %}
                                {% if messages %}
                                <div class="form-group">
                                <div class="col-12">
                                    {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                </div>
                                {% endif %}
                            
                    <form method="POST" action="{% url 'base:staff_apply_leave_save' %}">
                        {% csrf_token %}
                        <div class="card-body">
                           
                            <div class="form-group">
                                <label>Leave Date </label>
                                <input type="date" name="leave_date" class="form-control" />
                            </div>

                            <div class="form-group">
                                <label>Leave Reason </label>
                                <textarea name="leave_message" class="form-control" rows="6" placeholder="Leave Messge"></textarea>
                            </div>


                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Apply for Leave</button>
                        </div>

                    </form>

                    </div>
                    <!-- /.card -->



                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">Leave Apply History</h3>
                        </div>

                        <div class="card-body">
                           <div class="table-responsive">
                                <table class="table">
                                    <thead class="thead-light">
                                    <tr>
                                        <th>#ID</th>
                                        <th>Leave Date</th>
                                        <th>Leave Message</th>
                                        <th>Status</th>
                                    </tr>
                                    </thead>
                                    
                                    {% for leave in leave_data %}
                                    <tr>
                                        <td>{{ leave.id }}</td>
                                        <td>{{ leave.leave_date }}</td>
                                        <td>{{ leave.leave_message }}</td>
                                        <td>
                                            {% if leave.leave_status == 1 %}
                                                <span class="alert alert-success">Approved</span>
                                            {% elif leave.leave_status == 2 %}
                                                <span class="alert alert-danger">Rejected</span>
                                            {% else %}
                                                <span class="alert alert-warning">Pending</span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

{% endblock %}

{% block custom_js %}

{% endblock custom_js %}

templates/privetchat/staff_feedback_template.html
{% extends "../sub_base.html" %}
{% block title %}Edit Addresses{% endblock %}

{% block page_title %}
    Feedback Message
{% endblock page_title %}

{% block sub_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Leave a Feedback Message</h3>
                    </div>
                    <!-- /.card-header -->

                                {% comment %} Display Messages {% endcomment %}
                                {% if messages %}
                                <div class="form-group">
                                <div class="col-12">
                                    {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                </div>
                                {% endif %}
                            
                    <form method="POST" action="{% url 'base:staff_feedback_save' %}">
                        {% csrf_token %}
                        <div class="card-body">
                           
                            <div class="form-group">
                                <label>Feedback Message </label>
                                <textarea name="feedback_message" class="form-control" rows="6" placeholder="Feedback Message"></textarea>
                            </div>


                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Leave a Feedback</button>
                        </div>

                    </form>

                    </div>
                    <!-- /.card -->



                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">Feedback History</h3>
                        </div>

                        <div class="card-body">
                           <div class="table-responsive">
                                <table class="table">
                                    <thead class="thead-light">
                                    <tr>
                                        <th>#ID</th>
                                        <th>Feedback Message</th>
                                        <th>Feedback Reply</th>
                                    </tr>
                                    </thead>
                                    
                                    {% for row in feedback_data %}
                                    <tr>
                                        <td>{{ row.id }}</td>
                                        <td>{{ row.feedback }}</td>
                                        <td>{{ row.feedback_reply }}</td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

      {% endblock %}

{% block custom_js %}

{% endblock custom_js %}

templates/privetchat/staff_leave_view.html
{% extends "../sub_base.html" %}
{% block title %}Edit Addresses{% endblock %}

{% block page_title %}
    Leave Apply by Staffs
{% endblock page_title %}

{% block sub_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Leave Apply by Staffs</h3>
                        </div>
                        <!-- /.card-header -->

                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Staff ID</th>
                                    <th>Staff Name</th>
                                    <th>Leave Date</th>
                                    <th>Leave Message</th>
                                    <th>Applied On</th>
                                    <th>Action</th>
                                </tr>
                                </thead>

                                {% for leave in leaves %}
                                <tbody>
                                <tr>
                                    <td>{{ leave.id }}</td>
                                    <td>{{ leave.staff_id.admin.id }}</td>
                                    <td>{{ leave.staff_id.admin.name }} {{ feedback.staff_id.admin.last_name }}</td> 
                                    <td>{{ leave.leave_date }}</td>
                                    <td>{{ leave.leave_message }}</td>
                                    <td>{{ leave.created_at }}</td>
                                    <td>
                                        {% if leave.leave_status == 0 %}
                                            <a href="{% url 'base:staff_leave_approve' leave_id=leave.id %}" class="btn btn-success">Approve</a>
                                            <a href="{% url 'base:staff_leave_reject' leave_id=leave.id %}" class="btn btn-danger">Reject</a>
                                        {% elif leave.leave_status == 1 %}
                                            <button class="btn btn-warning" disabled="disabled">Approved</button>
                                        {% else %}
                                            <button class="btn btn-danger" disabled="disabled">Rejected</button>
                                        {% endif %}
                                        
                                    </td>
                                </tr>
                                </tbody>
                                {% endfor %}

                            </table>
                        </div>
                    
                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>



  {% endblock %}

  {% comment %} Custom JS to Identify the Reply and Post Reply {% endcomment %}

  {% block custom_js %}

  {% endblock custom_js %}

templates/privetchat/user_wish_list.html
{% extends "../sub_base.html" %}
{% block title %}Users Wish List{% endblock %}

{% block sub_content %}
<div class="col-12 mx-auto">
  <h1 class="h3">My Wishlist</h1>
  <div>Manage your Wishlist</div>
  <hr />

  {% if wishlist %}
  {% for product in wishlist  %}

  <div class="card mb-3 rounded-0">
    <div class="row g-0">
      <div class="col-md-2">
        {% for image in product.product_image.all  %}
          {% if image.is_feature %}
          <img class="img-fluid d-block p-2" width="135px" src="{{ image.image.url }}"
            alt="{{ image.image.alt_text }}" />
          {% endif %}
        {% endfor %}
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <h5 class="card-title">{{product.title}}</h5>
          <p class="card-text">{{product.description}}</p>
          <p class="card-text"><small class="text-muted">{{product.regular_price}}</small></p>
          <a type="button" class="btn btn-primary fw500 btn-sm" href="{% url 'account:user_wishlist' product.id %}">Remove from Wishlist</a>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
  {% else %}
  <p class="card-text">No products have been added to your wishlist yet</p>
  {% endif %}



</div>
{% endblock %}

templates/privetchat/users_feedback.html
{% extends "../sub_base.html" %}


{% block page_title %}
    Feedback Message
{% endblock page_title %}
{% block sub_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Leave a Message</h3>
                    </div>
                    <!-- /.card-header -->

                                {% comment %} Display Messages {% endcomment %}
                                {% if messages %}
                                <div class="form-group">
                                <div class="col-12">
                                    {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                </div>
                                {% endif %}
                            
                    <form method="POST" action="{% url 'base:users_feedback_save' %}">
                        {% csrf_token %}
                        <div class="card-body">
                           
                            <div class="form-group">
                                <label>Feedback Message </label>
                                <textarea name="feedback_message" class="form-control" rows="6" placeholder="Feedback Message"></textarea>
                            </div>


                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Leave a Feedback</button>
                        </div>

                    </form>

                    </div>
                    <!-- /.card -->



                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">Feedback History</h3>
                        </div>

                        <div class="card-body">
                           <div class="table-responsive">
                                <table class="table">
                                    <thead class="thead-light">
                                    <tr>
                                        <th>#ID</th>
                                        <th>Feedback Message</th>
                                        <th>Feedback Reply</th>
                                    </tr>
                                    </thead>
                                    
                                    {% for row in feedback_data %}
                                    <tr>
                                        <td>{{ row.id }}</td>
                                        <td>{{ row.feedback }}</td>
                                        <td>{{ row.feedback_reply }}</td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock  %}

{% block custom_js %}

{% endblock custom_js %}