account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView
from . import StaffViews, HodViews


from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm


app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logoutUser/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logoutUser"),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset/password_reset_confirm.html"
        ,success_url="password_reset_complete/",form_class=PwdResetConfirmForm,),
        name="password_reset_confirm",
    ),
    path("password_reset/password_reset_email_confirm/",TemplateView.as_view(template_name="account/password_reset/reset_status.html"),name="password_reset_done",),
    path("password_reset_confirm/Mg/password_reset_complete/",TemplateView.as_view(template_name="account/password_reset/reset_status.html"),name="password_reset_complete",),
    # # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path("profile/delete_confirm/",TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),name="delete_confirmation",),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),

    
]

base/urls.py
from django.urls import path
from . import views
from .views import doctor_list, doctor_detail
app_name = 'base'

urlpatterns = [


    path('', views.hospital_all, name='store_home'),
    path('hospital_all/', views.hospital_all, name='hospital_all'),
    path('dashboard-index/', views.index, name='dashboard-index'),
    # path('hospital/<slug:slug>/', views.map, name='hospital_map'),
    path('hospital<slug:slug>', views.hospital_detail, name='hospital_detail'),
    path('hospital/<slug:category_slug>/', views.category_list, name='category_list'),
    path('save_location/',views.save_location, name='save_location'),
    path('doctor-list/', doctor_list, name='doctor_list'),
    path('doctor-detail/<slug:slug>/', doctor_detail, name='doctor_detail'),
    path('staff_apply_leave/', views.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save/', views.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback/', views.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save/', views.staff_feedback_save, name="staff_feedback_save"),
    path('users_feedback_message/', views.users_feedback_message, name="users_feedback_message"),
    path('users_feedback_message_reply/', views.users_feedback_message_reply, name="users_feedback_message_reply"),
    path('staff_feedback_message/', views.staff_feedback_message, name="staff_feedback_message"),
    path('staff_feedback_message_reply/', views.staff_feedback_message_reply, name="staff_feedback_message_reply"),
    path('staff_leave_view/', views.staff_leave_view, name="staff_leave_view"),
    path('staff_leave_approve/<leave_id>/', views.staff_leave_approve, name="staff_leave_approve"),
    path('staff_leave_reject/<leave_id>/', views.staff_leave_reject, name="staff_leave_reject"),
    path('users_feedback/', views.users_feedback, name="users_feedback"),
    path('users_feedback_save/', views.users_feedback_save, name="users_feedback_save"),
    path("services/", views.services, name="services"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path('users_message/', views.users_message, name="users_message"),
    path('users_message_save/', views.users_message_save, name="users_message_save"),
    path('users_message_view/', views.users_message_view, name="users_message_view"),
    path('users_message_reply/', views.users_message_reply, name="users_message_reply"),


    
]

groupchat/urls.py
from django.urls import path
from . import views

app_name = 'groupchat'

urlpatterns = [
   
    path('home/', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),

    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),

    path('update-user/', views.updateUser, name="update-user"),

    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
]

map/urls.py
from django.urls import path
from .views import index
app_name = "map"

urlpatterns = [
    path('index/', index, name='index'),
]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls',namespace="base")),
    path('groupchat/', include('groupchat.urls' , namespace="groupchat")),
    path('account/', include('account.urls', namespace="account")),
    path('basket/', include('basket.urls', namespace="basket")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    path('privetchat/', include('privetchat.urls', namespace="privetchat")),
    path('promotion/', include('promotion.urls', namespace="promotion")),
    path('map/', include('map.urls', namespace="map")),
    path('api/', include('groupchat.api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from account.models import  Customer
from .models import Room


class MyUserCreationForm(BaseUserManager):
    class Meta:
        model = Customer
        fields = ['name', 'email', 'password1', 'password2']


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = Customer
        fields = [ 'name', 'email']

base/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from base.EmailBackEnd import EmailBackEnd
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.hashers import make_password
from django.core.files.storage import FileSystemStorage 
from django.shortcuts import render
from .models import Doctors,LeaveReportDoctors,MessageUser, Country,Hospital,FeedBackUser,FeedBackDoctors,Appointment
import folium
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from folium import plugins
from django.views.decorators.cache import cache_control
import json
import requests
from math import radians, sin, cos, sqrt, atan2
from account.models import Customer
from geopy import distance
from geopy.distance import geodesic
from django.http import JsonResponse

def submit_rating(request):
    if request.method == 'POST':
        rating = request.POST.get('rating')
        # Perform any validation or processing of the rating value here

        # Update the hospital_rating in your Django model accordingly
        # Assuming you have a Hospital model with a hospital_rating field
        hospital = Hospital.objects.get(pk=request.hospital)  # Replace 1 with the actual hospital record you want to update
        hospital.hospital_rating = rating
        hospital.save()

        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request method'})






def index(request):
    url = ("https://raw.githubusercontent.com/python-visualization/folium/main/examples/data")
    vis1 = json.loads(requests.get(f"{url}/vis1.json").text)
    vis2 = json.loads(requests.get(f"{url}/vis2.json").text)
    vis3 = json.loads(requests.get(f"{url}/vis3.json").text)
    data = Country.objects.all()
    data_list = Country.objects.values_list('latitude', 'longitude')

    map1 = folium.Map(location=[10.2116702, 38.6521203],
                      tiles='CartoDB Dark_Matter', zoom_start=8)
    tooltip = "Click me!"
    folium.Marker([10.2116702, 38.6521203], popup="<i>{{ country }}</i>", tooltip=tooltip).add_to(map1)
 
    map1 = folium.Map(location=[8.5410261, 39.2705461], zoom_start=7, tiles="Stamen Terrain")

    folium.Marker(location=[9.0107934, 38.7612525],popup=folium.Popup(max_width=450).add_child(folium.Vega(vis1, width=450, height=250)),).add_to(map1)

    folium.Marker(location=[8.286087, 37.781844],popup=folium.Popup(max_width=450).add_child(folium.Vega(vis2, width=450, height=250)),).add_to(map1)

    folium.Marker(location=[7.2116702, 40.6521203],popup=folium.Popup(max_width=450).add_child(folium.Vega(vis3, width=450, height=250)),).add_to(map1)
    #define the two points
    # point1 = (9.0107934, 38.7612525) # Portland, OR
    # point2 = (8.5410261, 39.2705461) # Seattle, WA
    # # calculate the distance between the points using the Haversine formula
    # R = 6373.0 # approximate radius of earth in km
    # lat1 = radians(point1[0])
    # lon1 = radians(point1[1])
    # lat2 = radians(point2[0])
    # lon2 = radians(point2[1])
    
    # dlon = lon2 - lon1
    # dlat = lat2 - lat1
    # a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    # c = 2 * atan2(sqrt(a), sqrt(1 - a))
    
    # distance = R * c
    # # create a Folium map and add markers for the two points
    # map1 = folium.Map(location=[point1[0], point1[1]], zoom_start=6)
    # folium.Marker(location=[point1[0], point1[1]], popup='Point 1').add_to(map1)
    # folium.Marker(location=[point2[0], point2[1]], popup='Point 2').add_to(map1)
    #  # add a popup with the distance between the points
    # folium.Popup(f'Distance between points: {distance:.2f} km').add_to(folium.PolyLine(locations=[point1, point2]))


    plugins.HeatMap(data_list).add_to(map1)
    plugins.Fullscreen(position='topright').add_to(map1)
    map1 = map1._repr_html_()
    context = {
        'map1': map1
    }
    return render(request, 'store/map.html', context)





def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    hospitals = Hospital.objects.filter(
        category__in=Category.objects.get(name=category_slug).get_descendants(include_self=True)
    )
    return render(request, "store/category.html", {"category": category, "hospitals": hospitals})

def hospital_all(request):
    if 'q' in request.GET:
        q = request.GET['q']
        multiple_q = Q(Q(name__icontains=q)| Q(title__icontains=q) | Q(specialties_services__icontains=q) | Q(location__icontains=q)| Q(equiments__icontains=q))
        hospitals = Hospital.objects.prefetch_related("hospital_image").filter(multiple_q, is_active=True)
    else:
        hospitals = Hospital.objects.prefetch_related("hospital_image").filter(is_active=True)
    doctors = Doctors.objects.all()
    hospital_count = hospitals.count()
    context = {"hospitals": hospitals, 'hospital_count':hospital_count,'doctors':doctors}
    return render(request, "store/index.html", context)


def calculate_distance(point1, point2):
    return geodesic(point1, point2).kilometers



def hospital_detail(request, slug):
    hospital = get_object_or_404(Hospital, slug=slug, is_active=True)
    # Define the reference location
    ref_location = (7.6792877, 36.853324750435384)
    hospitals = Hospital.objects.all()
    hospital_rating = 4.8

    query = request.GET.get('q')  # Get the search query from the request

    if query:
        hospitals = search_hospitals(query)
    # Calculate the distance from the reference location to the hospital location
    hospital_location = (hospital.latitude, hospital.longitude)
    distance_to_hospital = calculate_distance(ref_location, hospital_location)

    # Create a folium map for the hospital location
    hospital_map = folium.Map(location=hospital_location, zoom_start=7)
    folium.Marker(location=hospital_location, popup=hospital.location).add_to(hospital_map)

    # Add the distance from the reference location to the hospital location as a popup message
    popup_message = f"Distance from reference location: {distance_to_hospital:.2f} km"
    folium.Marker(location=ref_location, popup=popup_message, icon=folium.Icon(color='red')).add_to(hospital_map)

    # Generate the HTML code for the map
    map_html = hospital_map._repr_html_()
    #search
    
    
    


    # Pass the folium maps to the template
    context = {"hospital": hospital, 'map_html': map_html,'query': query,'hospital_rating': hospital_rating}
    return render(request, "store/single.html", context)





# def map(request,slug):
#     hospital = get_object_or_404(Country, slug=slug, is_active=True)
#     ref_location = (13.4966644, 39.4768259)

#     # Retrieve all hospitals from the database
    

#     # Create a folium map for each hospital
#     maps = []
#     for hospital in hospitals:
#         # Calculate the distance from the reference location to the hospital location
#         hospital_location = (hospital.latitude, hospital.longitude)
#         distance_to_hospital = calculate_distance(ref_location, hospital_location)

#         # Create a folium map for the hospital location
#         hospital_map = folium.Map(location=hospital_location, zoom_start=15)
#         folium.Marker(location=hospital_location, popup=hospital.country).add_to(hospital_map)

#         # Add the distance from the reference location to the hospital location as a popup message
#         popup_message = f"Distance from reference location: {distance_to_hospital:.2f} km"
#         folium.Marker(location=ref_location, popup=popup_message, icon=folium.Icon(color='red')).add_to(hospital_map)

#         maps.append(hospital_map._repr_html_())

#     # Generate the HTML code for the maps
#     maps_html = "".join(maps)

#     context = {'maps_html': maps_html}
#     return render(request, "store/single.html", context)


def submit_rating(request):
    if request.method == 'POST':
        rating = request.POST.get('rating')
        # Perform any validation or processing of the rating value here

        # Update the hospital_rating in your Django model accordingly
        # Assuming you have a Hospital model with a hospital_rating field
        hospital = Hospital.objects.get(pk=1)  # Replace 1 with the actual hospital record you want to update
        hospital.hospital_rating = rating
        hospital.save()

        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request method'})




@csrf_exempt
def save_location(request):
    
    if request.method == 'POST':
        latitude = request.POST.get('latitude')
        longitude = request.POST.get('longitude')

        # save the user's location to the database or perform any other necessary actions

        return HttpResponse('Location saved successfully')



def doctor_list(request):
    doctors = Doctors.objects.all()
    return render(request, 'store/doctor_list.html', {'doctors': doctors})

def doctor_detail(request, slug):
    doctor = get_object_or_404(Doctors, slug=slug)
    appointments = Appointment.objects.filter(doctor=doctor)
    return render(request, 'store/doctor_detail.html', {'doctor': doctor, 'appointments': appointments})







def home(request):
    # hospitals = Hospital.objects.prefetch_related("hospital_image").filter(is_active=True)
    # hospital_count = hospitals.count()
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )

    topics = Topic.objects.all()[0:5]
    room_count = rooms.count()

templates/bas1e.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}Web Based Ethiopian Health Guidance and Location Service with Map{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "icheck-bootstrap/icheck-bootstrap.min.css" %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static "jqvmap/jqvmap.min.css" %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'  %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "overlayScrollbars/css/OverlayScrollbars.min.css" %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static "daterangepicker/daterangepicker.css" %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static "summernote/summernote-bs4.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


</head>



{% block content %}


{% endblock %}

<!-- jQuery -->
<script src="{% static "jquery/jquery.min.js"  %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "jquery-ui/jquery-ui.min.js"  %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js"  %}"></script>
<!-- ChartJS -->
<script src="{% static "chart.js/Chart.min.js"  %}"></script>
<!-- Sparkline -->
<script src="{% static "sparklines/sparkline.js"  %}"></script>
<!-- JQVMap -->
<script src="{% static "jqvmap/jquery.vmap.min.js"  %}"></script>
<script src="{% static "jqvmap/maps/jquery.vmap.usa.js"  %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "jquery-knob/jquery.knob.min.js"  %}"></script>
<!-- daterangepicker -->
<script src="{% static "moment/moment.min.js"  %}"></script>
<script src="{% static "daterangepicker/daterangepicker.js"  %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"  %}"></script>
<!-- Summernote -->
<script src="{% static "summernote/summernote-bs4.min.js"  %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "overlayScrollbars/js/jquery.overlayScrollbars.min.js"  %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js'  %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js'  %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js'  %}"></script>
</body>
</html>

templates/email_confirmation.html
{% autoescape off %}

 Welcome to GFG - Django Login!!
 Hello {{ name }}!!
 Please confirm your email by clicking on the following link.

 Confirmation Link: http://{{ domain }}{% url 'activate' uidb64=uid token=token %} 

 {% endautoescape %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <title>StudyBuddy - Find study partners around the world!</title>
</head>

<body>

    {% include 'navbar.html' %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block content %}


    {% endblock %}

 <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/navbar.html
{% load static %}
<header class="header header--loggedIn">
    <div class="container">
        <a href="{% url 'base:store_home' %}" class="header__logo">
            <img src="{% static 'images/logo.svg' %}" />
            <h1>Chat With Doctors</h1>
        </a>
        <form class="header__search" method="GET" action="{% url 'groupchat:home' %}">
            <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>search</title>
                    <path
                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
                    </path>
                </svg>
                <input name="q" placeholder="Search for posts" />
            </label>
        </form>
        <nav class="header__menu">


            <!-- Logged In -->
            {% if request.user.is_authenticated %}
            <div class="header__user">
                <a href="{% url 'groupchat:update-user' %}">
                    <div class="avatar avatar--medium active">
                        <img src="{{request.user.avatar.url}}" />
                    </div>
                    <p>{{request.user.username}} <span>@{{request.user.name}}</span></p>
                </a>
                <button class="dropdown-button">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>chevron-down</title>
                        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
                    </svg>
                </button>
            </div>
            {% else %}

            <!-- Not Logged In -->
            <a href="{% url 'account:login' %}">
                <img src="{% static 'images/avatar.svg' %}" />
                <p>Login</p>
            </a>
            {% endif %}

            <div class="dropdown-menu">
                <a href="{% url 'account:logoutUser' %}" class="dropdown-link"><svg version="1.1"
                        xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>tools</title>
                        <path
                            d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z">
                        </path>
                    </svg>
                    Settings</a>
                <a href="{% url 'account:logoutUser' %}" class="dropdown-link"><svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                        width="32" height="32" viewBox="0 0 32 32">
                        <title>sign-out</title>
                        <path
                            d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z">
                        </path>
                        <path
                            d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z">
                        </path>
                    </svg>
                    Logout</a>
            </div>
        </nav>
    </div>
</header>